
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 27 21:33:35 CST 2024
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 36;
  public static final int Entero = 12;
  public static final int Incremento = 26;
  public static final int Coma = 10;
  public static final int Sum = 15;
  public static final int If = 39;
  public static final int Res_Igual = 23;
  public static final int Void = 49;
  public static final int Diferente = 35;
  public static final int Llave_Abierta = 28;
  public static final int Decremento = 27;
  public static final int Default = 45;
  public static final int Else = 40;
  public static final int Menor = 34;
  public static final int Mul_Igual = 24;
  public static final int Read = 47;
  public static final int Break = 46;
  public static final int Error = 14;
  public static final int Mayor_Igual = 31;
  public static final int Mayor = 32;
  public static final int PuntoYComa = 9;
  public static final int Res = 16;
  public static final int Long = 3;
  public static final int P_Cerrado = 21;
  public static final int Return = 50;
  public static final int While = 42;
  public static final int Int = 2;
  public static final int Menor_Igual = 33;
  public static final int For = 41;
  public static final int Div_Igual = 25;
  public static final int EOF = 0;
  public static final int DosPuntos = 11;
  public static final int Not = 38;
  public static final int And = 37;
  public static final int error = 1;
  public static final int Switch = 43;
  public static final int Char = 5;
  public static final int Div = 18;
  public static final int Do = 51;
  public static final int Continue = 52;
  public static final int Case = 44;
  public static final int Short = 4;
  public static final int Const = 6;
  public static final int P_Abierto = 20;
  public static final int Mul = 17;
  public static final int Sum_Igual = 22;
  public static final int Identificador = 7;
  public static final int Llave_Cerrada = 29;
  public static final int Mod = 19;
  public static final int Caracter = 13;
  public static final int Write = 48;
  public static final int Igual = 8;
  public static final int Igual_Igual = 30;
}

